import java.text.DecimalFormat;
import java.util.Random;
import javax.swing.JOptionPane;

public class NumberGame extends javax.swing.JFrame {

    /**
     * Creates new form NumberGame1
     */
    
    int Number1 = 0, Number2=0, Operator=0;
    String OperatorLiteral = "";
    public NumberGame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jlbl_Display = new javax.swing.JLabel();
        jTxt_Ans = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Jlbl_Display.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        Jlbl_Display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlbl_Display.setText("000 + 000 =");

        jTxt_Ans.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jTxt_Ans.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Jlbl_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxt_Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Jlbl_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(Operator == 3){
                double ans = Double.parseDouble(jTxt_Ans.getText());
                if(ans == Double.parseDouble(Solve("calc"))){
                    check("CORRECT");
                }else{
                    check("wrong");
                }
            }else{
                int ans = Integer.parseInt(jTxt_Ans.getText());
                if(ans == Integer.parseInt(Solve("calc"))){
                    check("CORRECT");
                }else{
                    check("wrong");
                }
            }
        } catch (NumberFormatException e) {
            int option = JOptionPane.showOptionDialog(this, "Input is invalid! Please enter a valid number.", "Invalid", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
            if(option == JOptionPane.OK_OPTION){
                jTxt_Ans.setText("");
            }            
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void check(String prompt){
        if(prompt == "CORRECT"){
            JOptionPane.showOptionDialog(this, "Your answer is CORRECT!", "Correct", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
        }else{
            JOptionPane.showOptionDialog(this, "Your answer is WRONG", "Wrong", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);     
        }
        
        int again = JOptionPane.showOptionDialog(this, "Answer another expression?", "Retry?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(again == JOptionPane.YES_OPTION){
            jTxt_Ans.setText("");
            setRandomNumbers();
        }    
    }
    
    private void setRandomNumbers(){
        Number1 = (int) (Math.random() * ((10-1)+1)+1);
        Number2 = (int) (Math.random() * ((10-1)+1)+1) ;
        Operator = (int) (Math.random() * 4);      
        Jlbl_Display.setText(Number1 + " " + Solve("getOperator") + " " + Number2 + " =");
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setRandomNumbers();
    }//GEN-LAST:event_formWindowOpened

    private String Solve(String prompt){
        String ans = "";
        if(Operator == 0){
            ans = Integer.toString(Number1 + Number2);
            OperatorLiteral = "+";
        }else if (Operator == 1){
            ans = Integer.toString(Number1 - Number2);
            OperatorLiteral = "-";
        }else if (Operator == 2){
            ans = Integer.toString(Number1 * Number2);
            OperatorLiteral = "*";
        }else if (Operator == 3){
            ans = Double.toString((double)Number1 / Number2);
            OperatorLiteral = "/";
            DecimalFormat df = new DecimalFormat("#.##");
            ans = Double.toString(Double.valueOf(df.format(Double.parseDouble(ans))));
        }else{
            System.out.println("Error");
        }
        String returnValue ="";
        if(prompt == "calc"){
            returnValue = ans;
        }else{
            returnValue = OperatorLiteral;
            System.out.println(ans);
        }
        return returnValue;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumberGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumberGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumberGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumberGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlbl_Display;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTxt_Ans;
    // End of variables declaration//GEN-END:variables
}
